In [1]:
import torch
import numpy as np

In [2]:
A = torch.ones(2,3,4,5)
print(A)
print('\n',A.shape)

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])

 torch.Size([2, 3, 4, 5])


In [3]:
B = torch.Tensor(2,2,2)
print(B)
B.uniform_(-1,1)
print('\n',B)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

 tensor([[[-0.0184,  0.7938],
         [ 0.8233, -0.9780]],

        [[-0.5202,  0.9132],
         [ 0.4001, -0.8849]]])


In [4]:
C = torch.rand(2,2,2)
print(C)

tensor([[[0.1474, 0.0530],
         [0.4704, 0.9229]],

        [[0.6811, 0.6017],
         [0.9600, 0.9263]]])


In [5]:
print(C+B)
print('\n', C*B)

tensor([[[ 0.1290,  0.8468],
         [ 1.2937, -0.0551]],

        [[ 0.1609,  1.5150],
         [ 1.3601,  0.0413]]])

 tensor([[[-0.0027,  0.0421],
         [ 0.3873, -0.9026]],

        [[-0.3543,  0.5495],
         [ 0.3841, -0.8197]]])


In [6]:
print(f'{C}\n{C.shape}\n')
reshaped = C.view(4,2)
print(f'{reshaped}\n{reshaped.shape}')


tensor([[[0.1474, 0.0530],
         [0.4704, 0.9229]],

        [[0.6811, 0.6017],
         [0.9600, 0.9263]]])
torch.Size([2, 2, 2])

tensor([[0.1474, 0.0530],
        [0.4704, 0.9229],
        [0.6811, 0.6017],
        [0.9600, 0.9263]])
torch.Size([4, 2])


In [7]:
points = torch.tensor([[1.,2.], [3.,4.]])
print(points)
points[0][1] = 5
print(points)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 5.],
        [3., 4.]])


In [8]:
print(points.storage())
print('\n',C.storage())
print('\n',reshaped.storage())

1.0
 5.0
 3.0
 4.0
[torch.FloatStorage of size 4]

  0.1474187970161438
 0.05297815799713135
 0.47036033868789673
 0.9228739738464355
 0.681066632270813
 0.6017235517501831
 0.9600489735603333
 0.9262747168540955
[torch.FloatStorage of size 8]

  0.1474187970161438
 0.05297815799713135
 0.47036033868789673
 0.9228739738464355
 0.681066632270813
 0.6017235517501831
 0.9600489735603333
 0.9262747168540955
[torch.FloatStorage of size 8]


In [9]:
print(C.stride())
print('\n', reshaped.stride())
print(f'\n{points.stride()}\n\n{points.t().stride()}')

(4, 2, 1)

 (2, 1)

(2, 1)

(1, 2)


In [10]:
X = torch.tensor([1,2,3,4])
print(X)
print('\n',torch.unsqueeze(X, 0))
print('\n',torch.unsqueeze(X, 1))
print('\n',torch.unsqueeze(X, 2))

tensor([1, 2, 3, 4])

 tensor([[1, 2, 3, 4]])

 tensor([[1],
        [2],
        [3],
        [4]])


IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [11]:
array = np.random.randn(2,2)
from_np = torch.from_numpy(array)

# Representar datos con tensores

In [12]:
print(points)
print('\n',torch.mean(points))
print('\n',torch.mean(points,dim=0))
print('\n',torch.mean(points,dim=1))

tensor([[1., 5.],
        [3., 4.]])

 tensor(3.2500)

 tensor([2.0000, 4.5000])

 tensor([3.0000, 3.5000])


In [13]:
print(points)
print('\n',torch.std(points))
print('\n',torch.std(points,dim=0))
print('\n',torch.std(points,dim=1))

tensor([[1., 5.],
        [3., 4.]])

 tensor(1.7078)

 tensor([1.4142, 0.7071])

 tensor([2.8284, 0.7071])


In [14]:
torch.save(points, 'pytorch_tensor')